--- #YAML:1.0
name:               Collision-2D
version:            0.03
abstract:           A selection of continuous collision detection routines
author:
    - Zach Morgan <zpmorgan@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::AllUtils:       0
    Mouse:                0
    Test::More:           0
    Test::Number::Delta:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
